import "../../styles/global.css";

import Footer from "@/layout/footer";
import Header from "@/layout/header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="pt-32 pb-30">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
